// The Frequency Library — real phenomena, three layers each:
// poetic truth / scientific truth / try it now.
// No fake healing frequencies. Hedged, honest science; beautiful language.
//
// Entry shape:
//   { id, title, glyph, hue, hook, poetic, science, tryIt,
//     related: { stateId, practiceId, label } | null }

const LIBRARY = [
  {
    id: 'sound-is-vibration',
    title: 'Sound is vibration',
    glyph: '♒',
    hue: 195,
    hook: 'every sound is something trembling',
    poetic: 'Every sound you have ever loved was something trembling — a string, a throat, a drum skin, the air itself. Hearing is touch at a distance.',
    science: 'Sound is a pressure wave: vibrating objects push air molecules back and forth, and your eardrum physically moves with them. Pitch is how fast the vibration repeats; loudness is how hard it pushes.',
    tryIt: 'Rest your fingertips lightly on your throat and speak one slow sentence. That buzz is the literal, physical vibration your voice is made of.',
    related: null,
  },
  {
    id: 'resonance',
    title: 'Resonance',
    glyph: '◎',
    hue: 275,
    hook: 'some things wake up when the right note finds them',
    poetic: 'Some things wake up when the right note finds them. A wine glass, a guitar string across the room, a person hearing exactly the sentence they needed.',
    science: 'Every object has frequencies it naturally vibrates at. When incoming energy matches one, the object absorbs it efficiently and vibrates strongly — that’s resonance. It’s why a singer’s note can rattle a glass and why your chest hums along at some concerts.',
    tryIt: 'Hum low, then slide your hum slowly higher. Notice how the buzz moves — chest, throat, teeth, skull. You’re finding the resonant spaces of your own body.',
    related: { stateId: 'overstimulated', practiceId: 'lower-the-signal', label: 'Tune with humming' },
  },
  {
    id: 'entrainment',
    title: 'Entrainment',
    glyph: '∿',
    hue: 160,
    hook: 'rhythms that meet tend to sync',
    poetic: 'Put two rhythms in the same room and they start negotiating. Pendulum clocks on a shared wall. Footsteps of people walking together. You, breathing slower because the music did.',
    science: 'Entrainment is the tendency of rhythmic systems to synchronize when coupled. In people, breathing, heart rate, and movement can shift toward external rhythms — slow music and paced breathing tend to pull the body’s tempo down with them.',
    tryIt: 'Play any slow song and tap the beat on your knee for one minute. Then notice what your breath did while you weren’t watching it.',
    related: { stateId: 'restless', practiceId: 'give-it-somewhere-to-go', label: 'Tune with rhythm' },
  },
  {
    id: 'breath-rhythm',
    title: 'Breath rhythm',
    glyph: '〰',
    hue: 185,
    hook: 'the one dial you can always reach',
    poetic: 'Of all the rhythms running you — heartbeat, hormones, sleep, hunger — breath is the only one that hands you the dial. It runs itself until you take the wheel.',
    science: 'Breathing is controlled automatically but can be overridden voluntarily, which makes it a direct lever on the autonomic nervous system. Slow breathing with extended exhales increases parasympathetic (rest-and-settle) activity; faster, fuller breathing shifts things toward alertness.',
    tryIt: 'One physiological sigh: two inhales through the nose — a big one, then a small top-up — followed by one long sighing exhale through the mouth. It’s one of the fastest known ways to take the edge off.',
    related: { stateId: 'heavy', practiceId: 'let-the-ground-hold-it', label: 'Tune with long exhales' },
  },
  {
    id: 'heart-rate-variability',
    title: 'Heart rate variability',
    glyph: '♡',
    hue: 350,
    hook: 'a healthy heart doesn’t keep perfect time',
    poetic: 'A healthy heart is not a metronome. It speeds and slows in tiny waves, listening to your breath, your feelings, the room. The flexibility is the health.',
    science: 'Heart rate variability (HRV) is the natural beat-to-beat variation in heart rhythm. Higher variability generally reflects a responsive, well-regulated nervous system. Your heart naturally speeds slightly on the inhale and slows on the exhale — slow breathing makes that wave bigger.',
    tryIt: 'Find your pulse at your wrist. Take a slow deep inhale, then a very slow exhale. Many people can feel the beat ease off as the exhale unwinds.',
    related: null,
  },
  {
    id: 'circadian-rhythm',
    title: 'Circadian rhythm',
    glyph: '☉',
    hue: 45,
    hook: 'you contain a clock older than clocks',
    poetic: 'You contain a clock older than clocks — wound by sunlight, sensitive to dusk, quietly scheduling your courage, your appetite, your sleep.',
    science: 'Nearly every cell in your body runs on a roughly 24-hour cycle coordinated by a master clock in the brain, which is set primarily by light hitting the eyes. Morning light strengthens the rhythm; bright light late at night pushes it later and can degrade sleep.',
    tryIt: 'Tomorrow, get outside light in your eyes within an hour of waking (no sunglasses, don’t stare at the sun). Note your energy at 3pm. Do it three days running and compare.',
    related: { stateId: 'low-energy', practiceId: 'kindle', label: 'Tune with light' },
  },
  {
    id: 'brain-waves',
    title: 'Brain waves, carefully',
    glyph: '⌇',
    hue: 252,
    hook: 'real rhythms, oversold powers',
    poetic: 'Your brain does hum in rhythms — slower ones in deep sleep, faster ones in sharp focus. That part is real. The posters that promise enlightenment at a specific frequency? Those are selling incense by the hertz.',
    science: 'EEG recordings show rhythmic electrical activity that changes with state: slower patterns dominate deep sleep and drowsiness; faster ones show up with alertness and effort. These are useful descriptions of brain states — but listening to a tone at some frequency doesn’t simply install the matching state, whatever the app store says.',
    tryIt: 'Notice your mental "speed" right now — racing, ticking, or syrup? Just naming the tempo is a real observation of brain state. No headset required.',
    related: null,
  },
  {
    id: 'music-and-emotion',
    title: 'Music & emotion',
    glyph: '♪',
    hue: 322,
    hook: 'organized vibration, straight to the feelings',
    poetic: 'Music is organized vibration with a passkey to the parts of you that words have to knock politely to enter.',
    science: 'Music engages emotion, memory, movement, and reward systems together — it can shift heart rate and breathing, trigger chills, and change mood measurably. Tempo, familiarity, and personal history all matter, which is why one person’s calming song is another’s grating noise.',
    tryIt: 'Pick the song you’d play a friend to explain how today feels. Play it. That’s emotional granularity — using sound to say the unsayable.',
    related: null,
  },
  {
    id: 'light-and-mood',
    title: 'Light & mood',
    glyph: '☼',
    hue: 38,
    hook: 'the room’s brightness is talking to your brain',
    poetic: 'You are a creature that reads the sky. Dim rooms whisper "wind down"; morning light says "begin"; and your body believes the lighting long before you’ve formed an opinion.',
    science: 'Light is electromagnetic radiation, and special receptors in the eye feed brightness information to circuits regulating alertness, mood, and the body clock. Bright daytime light supports mood and energy; dimming in the evening supports sleep.',
    tryIt: 'Tonight, an hour before bed, dim your main lights and any screens. Notice whether sleep arrives more like a guest and less like a negotiation.',
    related: null,
  },
  {
    id: 'everything-is-moving',
    title: 'Everything is moving',
    glyph: '✦',
    hue: 210,
    hook: 'stillness is a story we tell at our scale',
    poetic: 'The table is trembling. The stone is a slow blur. Stillness is a story matter tells at your scale — underneath, everything you’ve ever touched is dancing in place.',
    science: 'Atoms and molecules are in constant motion; temperature is a measure of that motion’s average energy. Heat you feel is molecular jostling passed to your skin. Nothing above absolute zero is truly still — though this is thermal physics, not evidence that objects carry moods.',
    tryIt: 'Hold something metal, then something wooden. The metal feels colder not because it is, but because it conducts your heat away faster. You just measured molecular physics with your palm.',
    related: null,
  },
  {
    id: 'why-humming-feels-holy',
    title: 'Why humming feels holy',
    glyph: 'ॐ',
    hue: 285,
    hook: 'chant, om, lullaby — same instrument',
    poetic: 'Monks chant, congregations hum, mothers lullaby half-asleep. Every tradition found the same instrument in the body and called it something different.',
    science: 'Humming pairs extended exhales (which calm the nervous system via the vagus nerve) with felt vibration in the chest, throat, and face — steady sensory input to rest attention on. Group humming or chanting adds synchronized breathing, which tends to feel bonding.',
    tryIt: 'One minute of low humming, eyes closed. Follow the vibration around your body like you’re tracing it with a finger.',
    related: { stateId: 'overstimulated', practiceId: 'lower-the-signal', label: 'Tune with humming' },
  },
  {
    id: 'why-drums-get-in',
    title: 'Why drums get into the body',
    glyph: '◉',
    hue: 14,
    hook: 'rhythm is muscle memory’s native tongue',
    poetic: 'A drum doesn’t ask permission. It walks past thought, taps the spine, and the foot answers before you’ve voted on it.',
    science: 'Rhythm engages motor circuits directly — the brain predicts the next beat and readies movement for it, which is why toes tap involuntarily. Low frequencies are also felt in the body as physical vibration, not just heard.',
    tryIt: 'Drum a slow steady beat on your thighs, both hands. After 30 seconds, slow it down gradually and let your breath follow the tempo down.',
    related: { stateId: 'restless', practiceId: 'give-it-somewhere-to-go', label: 'Tune with a beat' },
  },
  {
    id: 'why-silence-feels-loud',
    title: 'Why silence can feel loud',
    glyph: '◌',
    hue: 225,
    hook: 'the ear turns up the volume in an empty room',
    poetic: 'Step into deep quiet and the ears lean in, straining, until you can hear your own blood making weather. Silence isn’t empty. It’s just you, unmuffled.',
    science: 'In very quiet settings the auditory system increases sensitivity, and internal sounds — heartbeat, breath, ear noise — become noticeable. For minds used to constant input, quiet also removes distraction from thoughts and feelings, which can feel loud in its own way. That’s a normal reaction, not a failure of the silence or of you.',
    tryIt: 'Sit in the quietest spot available for two minutes. List every sound that’s actually still there. Quiet has a texture once you stop calling it nothing.',
    related: { stateId: 'weird', practiceId: 'take-a-reading', label: 'Tune with a reading' },
  },
];
